server:
  port: 8082   # Cổng chạy service client

spring:
  application:
    name: order-service   # Tên service sẽ hiển thị trên Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db   # URL kết nối PostgreSQL
    username: postgres                             # Username PostgreSQL
    password: 123456$                         # Password PostgreSQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # Tùy chọn: create, update, validate, none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Địa chỉ Eureka Server
    register-with-eureka: true   # Client sẽ đăng ký với Eureka
    fetch-registry: true         # Client sẽ lấy danh sách service từ Eureka
# câu hình resilience4j
resilience4j:
  circuitbreaker: # CLOSED , OPEN, HALF_OPEN
    instances:
      serviceA:
        sliding-window-size: 10 # theo dõi 10 cuộc gọi lần nhất để đánh giá có nên mở mạch hay ko
        sliding-window-type: count_based # số lần gọi
        failure-rate-threshold: 50 # % số lần gọi thất bại thì sẽ tự mở mach
        wait-duration-in-open-state: 15s # trong thời gian mở mạch chỉ luôn luôn gọi hàm fallback
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      retryService:
        max-attempts: 3 # số lần thử lại khi lỗi (tính cả lần lỗi đầu tiên)
        wait-duration: 3s # khoang nghỉ giữa các lần thử lại
        retry-exceptions:
          - java.lang.RuntimeException
  ratelimiter:
    instances:
      rateLimiterService:
        limit-for-period: 5 # số lần gọi tối đa trong 1 khoảng thời gian
        limit-refresh-period: 10s # khoảng thời gian giới hạn số lần gọi
        timeout-duration: 0s # thời gian chờ khi vượt quá giới hạn
  bulkhead:
    instances:
      timeOutService:
        max-concurrent-calls: 5 # số lượng cuộc gọi đồng thời tối đa
        max-wait-duration: 2s